x-default: &default
  restart: unless-stopped
  networks:
  - common
  env_file:
  - .env
  depends_on:
    python_base:
      condition: service_completed_successfully

x-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 30s

services:
  auth_app_backend:
    <<: *default
    build: .
    depends_on:
      auth_postgres:
        condition: service_healthy
    healthcheck:
      test: [CMD-SHELL, 'curl --fail http://localhost:${APP_PORT}${APP_ROOT_PATH}/api/v1/check || exit 1']
    expose:
    - ${APP_PORT}

  auth_postgres:
    <<: *default
    image: postgres:${POSTGRES_VERSION}
    healthcheck:
      test: [CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' || exit 1"]
      <<: *default-healthcheck
    volumes:
    - auth_pg_data:/var/lib/postgresql/data
    expose:
    - ${POSTGRES_PORT}
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  auth_pg_data:

networks:
  common:
    name: common
