"""initial migration

Revision ID: bfdc00968695
Revises:
Create Date: 2025-02-23 19:31:42.395345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bfdc00968695"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("external_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("external_user_id"),
    )
    op.create_index("ix_user_created_at", "user", ["created_at"], unique=False)
    op.create_table(
        "file",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user.external_user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_name"), "file", ["name"], unique=False)
    op.create_index("ix_file_name_trgm", "file", ["name"], unique=False)
    op.create_index(op.f("ix_file_owner_id"), "file", ["owner_id"], unique=False)
    op.create_index("ix_file_owner_ver", "file", ["owner_id", "version_id"], unique=False)
    op.create_index(op.f("ix_file_version_id"), "file", ["version_id"], unique=False)
    op.create_table(
        "file_version",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint("octet_length(checksum) = 64", name="checksum_length"),
        sa.CheckConstraint("version > 0", name="version_positive"),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_file_version", "file_version", ["file_id", "version"], unique=True)
    op.create_index(op.f("ix_file_version_checksum"), "file_version", ["checksum"], unique=False)
    op.create_index(op.f("ix_file_version_file_id"), "file_version", ["file_id"], unique=False)
    op.create_index(op.f("ix_file_version_path"), "file_version", ["path"], unique=False)
    op.create_index(op.f("ix_file_version_version"), "file_version", ["version"], unique=False)
    op.create_index("ix_filev_checksum", "file_version", ["checksum"], unique=False, postgresql_using="hash")
    op.create_index("ix_filev_size", "file_version", ["size"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_filev_size", table_name="file_version")
    op.drop_index("ix_filev_checksum", table_name="file_version", postgresql_using="hash")
    op.drop_index(op.f("ix_file_version_version"), table_name="file_version")
    op.drop_index(op.f("ix_file_version_path"), table_name="file_version")
    op.drop_index(op.f("ix_file_version_file_id"), table_name="file_version")
    op.drop_index(op.f("ix_file_version_checksum"), table_name="file_version")
    op.drop_index("ix_file_version", table_name="file_version")
    op.drop_table("file_version")
    op.drop_index(op.f("ix_file_version_id"), table_name="file")
    op.drop_index("ix_file_owner_ver", table_name="file")
    op.drop_index(op.f("ix_file_owner_id"), table_name="file")
    op.drop_index("ix_file_name_trgm", table_name="file")
    op.drop_index(op.f("ix_file_name"), table_name="file")
    op.drop_table("file")
    op.drop_index("ix_user_created_at", table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
