from typing import Protocol, TypeVar

from collections.abc import Sequence

from sqlalchemy import SelectBase

In_contra = TypeVar("In_contra", contravariant=True)
Out_in = TypeVar("Out_in")


class RepositoryProtocol(Protocol[In_contra, Out_in]):
    """Base CRUD repository interface"""

    async def upsert(self, obj: In_contra) -> Out_in: ...
    async def get(self, obj: In_contra) -> Out_in | None: ...
    async def update(self, obj: In_contra) -> Out_in: ...
    async def delete(self, obj: In_contra) -> None: ...
    async def bulk_create(self, objects: Sequence[Out_in]) -> None: ...
    async def exists(self, obj: In_contra) -> bool: ...
    async def get_all(self, statement: SelectBase | None) -> Sequence[Out_in]: ...
    async def get_by_statement(self, statement: SelectBase | None) -> Out_in | None: ...
